[package]
name = "switch_gcloud"
version = "0.1.0"
edition = "2021"
description  = "Rust CLI for switch gcloud."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
once_cell = "1"
